development: &development
  adapter: postgresql
  host: localhost
  database: mappd_dev
  encoding: unicode
  
test: &test
  adapter: postgresql
  host: localhost
  database: mappd_test
  encoding: unicode 
